commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

project/urls.py
from django.urls import path

from . import views
app_name = "savethehawkers"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("search", views.search, name = "search"),
    path("<int:pagenumber>/next", views.next, name = "next"),
    path("<int:pagenumber>/nextin", views.nextindex, name = "nextindex"),
    path("<int:pagenumber>/nextstall", views.nextstall, name = "nextstall"),
    path("stalltype", views.stalltype, name = "stalltype"),
    path("<str:name>/info", views.info, name = "info"),
    path("<str:name>/editing", views.edity, name="editing"),
    path("<str:name>/report", views.report, name="report"),
    path("creations", views.creations, name="creations"),
    path("<str:name>/comment", views.comment, name="comment"),
    path("<str:name>/profile", views.userprofile, name="users"),
    path("community", views.community, name="community"),
    path("bookmark/<str:name>", views.bookmark, name="bookmark"),
    path("groupbuy", views.groupbuy, name="groupbuy"),
    path("name", views.name, name="name"),
]

savethehawkers/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings

from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("project.urls")),
    #127.0.0.1:8000/media/9_grid_profile.png
    #127.0.0.1:8000/static/(project/hawk.png)
    url(r'^images/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

project/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.db.utils import Error
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
import numpy
import math

import telegram
from .models import *
from .models import User as UserProfile
from django import contrib, forms

from ipstack import GeoLookup
import requests
import json

from telegram import *
from django.conf import settings

import urllib

from datetime import date, datetime

from random import randrange

# NoReverseMatch: edity is not a name - probably didnt indicate app name in some html
# NoReverseMatch: argument (",") does not match.... - didnt include argument when your path requires one <str:...>
# NoReverseMatch: path does not exist - name you put is diff from "name" in urls
class CreateForm(forms.Form):
    postalcode = forms.IntegerField(label = "postalcode")
    image1 = forms.CharField(label = "image1", max_length = 200)
    name = forms.CharField(label = "name", max_length = 200)
    hours = forms.CharField(label = "hours", max_length = 300)
    reco = forms.CharField(label = "reco", max_length = 100)
    details = forms.CharField(label = "details", max_length = 1000)

class NewTaskForm (forms.Form):
    search = forms.CharField(label = "Food Recommendation:", min_length = 1, max_length = 50)
    postalcode = forms.IntegerField(label = "Postal Code:", min_value=1, max_value = 999999)

def distance(origin, destination):
 
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371  # km
 
    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2) * math.sin(dlat/2) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2) * math.sin(dlon/2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
    d = radius * c
 
    return d


def index(request):
    if request.method == "POST":
        history = History.objects.all()
        pagenumber = 1
        postalcode = request.POST["postalcode"]
        number = randrange(1,368)
        haw = HawkerStall.objects.filter(pk=number).first()
        # Error Tests
        if not postalcode:
            return render(request, "project/index.html",{
                "haw": haw,
                "message": "Enter a postal code.",
                "form": NewTaskForm(),
                "postalcode": postalcode,
                "pagenumber": pagenumber,
                "no": "no",
                "history": history,
            })
        try:
            val = int(postalcode)
        except ValueError:
            return render(request, "project/index.html",{
                "haw": haw,
                "message": "Please insert a number.",
                "form": NewTaskForm(),
                "postalcode": postalcode,
                "pagenumber": pagenumber,
                "no": "no",
                "history": history
            })
        try:
            address = f"https://developers.onemap.sg/commonapi/search?searchVal={postalcode}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
            response = requests.get(address)
            data = response.text
            parse_json = json.loads(data)
            latorigin = float(parse_json['results'][0]['LATITUDE'])
        except IndexError:
            return render(request, "project/index.html",{
                "haw": haw,
                "message": "Postal Code does not exist!",
                "form": NewTaskForm(),
                "postalcode": postalcode,
                "pagenumber": pagenumber,
                "no": "no",
                "history": history
            })    
            
        # Get values from API
        address = f"https://developers.onemap.sg/commonapi/search?searchVal={postalcode}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
        response = requests.get(address)
        data = response.text
        parse_json = json.loads(data)
        latorigin = float(parse_json['results'][0]['LATITUDE'])
        longorigin = float(parse_json['results'][0]['LONGITUDE'])
        place = parse_json['results'][0]['ADDRESS']

        # Calculate and sort distances to hawker stalls
        reco = request.POST['search']
        try:
            stalltypes = request.POST['stalltype']
            if not reco:
                hawk = HawkerStall.objects.filter(stalltype = stalltypes)
            else:
                hawk = HawkerStall.objects.filter(stalltype = stalltypes, reco__contains = reco)
        except KeyError:
            if not reco:
                hawk = HawkerStall.objects.all()
                stalltypes = 'x'
            else:
                hawk = HawkerStall.objects.filter(reco__contains = reco)
                stalltypes = 'x'
            
        


        number = [0] * len(hawk)
        count = 0
        for haw in hawk.iterator():
            lat = haw.latitude
            long = haw.longtitude
            origin = (latorigin, longorigin)
            destination = (lat, long)
            km = distance(origin, destination)
            km = km * 1000
            number[count] = round(km)
            count += 1
        #an array of the indexes after sorting
        
        s = numpy.array(number)
        sort_index = numpy.argsort(s)
        new_list = [x+1 for x in sort_index]
        number.sort()
        #number = [1093,2765,4021...]
        #new_list = [104,210,57...]
        latitudes = [0] * len(hawk)
        longtitudes = [0] * len(hawk)
        names = [0] * len(hawk)
        addresses = [0] * len(hawk)
        recos = [0] * len(hawk)
        hours = [0] * len(hawk)
        details = [0] * len(hawk)
        contributors = [0] * len(hawk)
        #hi
        # this will start from the numbers 4, then to 1, then to 6....
        if hawk == HawkerStall.objects.all():
            for i in new_list:
                for j in range(len(addresses)):
                    if addresses[j] != 0:
                        j = j+1
                    else:
                        ha = HawkerStall.objects.get(id = i)
                        latitudes[j] = ha.latitude
                        longtitudes[j] = ha.longtitude
                        names[j] = ha.name
                        addresses[j] = ha.address
                        recos[j] = ha.reco
                        hours[j] = ha.hours
                        details[j] = ha.details
                        contributors[j] = ha.contributor
                        break
        else:
            for i in sort_index:
                for j in range(len(addresses)):
                    if addresses[j] != 0:
                        j = j+1
                    else:
                        ha = hawk[int(i)]
                        latitudes[j] = ha.latitude
                        longtitudes[j] = ha.longtitude
                        names[j] = ha.name
                        addresses[j] = ha.address
                        recos[j] = ha.reco
                        hours[j] = ha.hours
                        details[j] = ha.details
                        contributors[j] = ha.contributor
                        break
        myhouselat = [latorigin] * len(hawk)
        myhouselong = [longorigin] * len(hawk)
        latandlong = zip(myhouselat, myhouselong, latitudes, longtitudes)
        latandlong2 = zip(myhouselat, myhouselong, latitudes, longtitudes)
        latandlong3 = zip(myhouselat, myhouselong, latitudes, longtitudes)
        latandlong4 = zip(myhouselat, myhouselong, latitudes, longtitudes)
        latandlong5 = zip(myhouselat, myhouselong, latitudes, longtitudes)
        latandlong6 = zip(myhouselat, myhouselong, latitudes, longtitudes)


        return render(request, "project/index.html",{
            "latorigin": latorigin,
            "longorigin": longorigin,
            "reco": reco,
            "stalltype": stalltypes,
            "postalcode": postalcode,
            "pagenumber": pagenumber,
            "latitudes": latitudes,
            "longtitudes": longtitudes,
            "names": names,
            "namesjson": json.dumps(names),
            "addresses": addresses,
            "recos": recos,
            "hours": hours,
            "details": details,
            "contributors": contributors,
            "numbers": number,
            "latandlong": latandlong,
            "latandlong2": latandlong2,
            "latandlong3": latandlong3,
            "latandlong4": latandlong4,
            "latandlong5": latandlong5,
            "latandlong6": latandlong6,
            "form": NewTaskForm()
        })
    
    comments = Comments.objects.all()
    history = History.objects.all()
    number = randrange(1,368)
    haw = HawkerStall.objects.filter(pk=number).first()
    hawk = HawkerStall.objects.all()
    numberoflistings = len(hawk)
    return render(request, "project/index.html",{
        "haw": haw,
        "no": "no",
        "form": NewTaskForm(),
        "history": history,
        "comments":comments,
        "numberoflistings": numberoflistings,
    })

def name(request):
    if request.method == "POST":
        name = request.POST['name']
        hawk = HawkerStall.objects.filter(name__contains = name)
        return render(request, "project/name.html", {
            "stalls": hawk,
        })

def nextindex(request, pagenumber):
    if request.method == "POST":
        page = int(pagenumber) + 1
        postalcode = request.POST["postalcode"]
            
        # Get values from API
        address = f"https://developers.onemap.sg/commonapi/search?searchVal={postalcode}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
        response = requests.get(address)
        data = response.text
        parse_json = json.loads(data)
        latorigin = float(parse_json['results'][0]['LATITUDE'])
        longorigin = float(parse_json['results'][0]['LONGITUDE'])
        place = parse_json['results'][0]['ADDRESS']

        stalltypes = request.POST['stalltype']

project/templates/project/create.html
{% extends "project/layout.html" %}

{% block body %}

<!-- Edit -->
{{message}}
<div class = "login">
<form action = "{%url 'savethehawkers:creations'%}" method = "POST">
    {%csrf_token%}
    Postal Code:{{form3.postalcode}} <br>
    Name:{{form3.name}} <br>
    Recommendation:{{form3.reco}} <br>
    Image URL from online:{{form3.image1}}
    <label for="stalltype">Stall Type:</label> <br>
    <select name="stalltype" id="stalltype">
        <option disabled selected value> Stall Type </option>
        <option value="Chinese">Chinese</option>
        <option value="Malay">Malay</option>
        <option value="Indian">Indian</option>
        <option value="Western">Western</option>
        <option value="Dessert">Dessert</option>
        <option value="Drinks">Drinks</option>
        <option value="Snacks">Snacks</option>
        <option value="Vegetarian">Vegetarian</option>
        <option value="Others">Others</option>
    </select>
    Hours: {{form3.hours}}
    Detail: {{form3.details}}
    Number: <input type = "number" name = "number">
    Halal: <input type = "checkbox" name = "halal">
    Contributor: You :)
    {%if user.is_authenticated%}
    <input type = "hidden" name = "contributor" value = "{{ user.username }}">
    {%else%}
    <input type = "hidden" name = "contributor" value = "Anonymous">
    {%endif%}
    <input type = "submit" value = "Create">
</form>
</div>
{% endblock %}

project/templates/project/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" ,maximum-scale=1">
        <link href="{% static 'project/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,500;0,800;1,300&display=swap"
            rel="stylesheet">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'project/typed.js' %}"></script>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
   <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap" rel="stylesheet">
   <!-- Make sure you put this AFTER Leaflet's CSS -->
 <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
 integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
 crossorigin=""></script>
 <script src="https://unpkg.com/scrollreveal"></script>
        <!-- Latest compiled and minified CSS -->
        <style>
            body {
              font-family: 'Inter', sans-serif;
            }
          </style>
          <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
        <title>SavetheHawkers</title>
    </head>
    <body>
        <header class="px-5 sm:px-10 md:px-10 md:py-5 lg:px-20 flex items-center justify-between">
            <div>
              <a href = "https://www.instagram.com/savethehawkers/"><img src="{% static 'project/logo.png' %}" class="w-48" style = "width: auto; height: 70px;"></a>
            </div>
            <div x-data="{ navOpen: false }">
              <button @click="navOpen = true">
                <svg class="cursor-pointer text-gray-700 hover:text-gray-900 w-6 md:hidden" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <line x1="3" y1="12" x2="21" y2="12"/>
                  <line x1="3" y1="6" x2="21" y2="6"/>
                  <line x1="3" y1="18" x2="21" y2="18"/>
                </svg>
              </button>
              <div :class="{'hidden': !navOpen}" class="md:block fixed top-0 inset-x-0 bg-white p-8 m-4 z-30 rounded-lg shadow md:rounded-none md:shadow-none md:p-0 md:m-0 md:relative md:bg-transparent">
                <button @click="navOpen = false" class="absolute top-0 right-0 mr-5 mt-5 md:hidden">
                  <svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
                    <path d="M18 6L6 18M6 6l12 12"/>
                  </svg>
                </button>
                <div class="flex flex-col items-center justify-center md:block">
                  <a href="{% url 'savethehawkers:index' %}" class="transition-all duration-100 ease-in-out pb-1 border-b-2 text-indigo-500 border-transparent hover:border-indigo-300
                  hover:text-gray-600 md:mr-8 text-lg md:text-sm font-bold tracking-wide my-4 md:my-0">
                    Home
                  </a>
                  <a href="{% url 'savethehawkers:community' %}" class="transition-all duration-100 ease-in-out pb-1 border-b-2 text-indigo-500 border-transparent hover:border-indigo-300
                  hover:text-indigo-600 md:mr-8 text-lg md:text-sm font-bold tracking-wide my-4 md:my-0">
                    Community
                  </a>
                  <a href="{% url 'savethehawkers:groupbuy' %}" class="transition-all duration-100 ease-in-out pb-1 border-b-2 text-indigo-500 border-transparent hover:border-indigo-300
                  hover:text-indigo-600 md:mr-8 text-lg md:text-sm font-bold tracking-wide my-4 md:my-0">
                    Group Buys
                  </a>
                  <a href="{% url 'savethehawkers:creations' %}" class="transition-all duration-100 ease-in-out pb-1 border-b-2 text-indigo-500 border-transparent hover:border-indigo-300
                  hover:text-indigo-600 md:mr-8 text-lg md:text-sm font-bold tracking-wide my-4 md:my-0">
                    Create Entry
                  </a>
                  {% if user.is_authenticated %}
                  <a href="{% url 'savethehawkers:logout' %}" class="transition-all duration-100 ease-in-out pb-1 border-b-2 text-indigo-500 border-transparent hover:border-indigo-300
                  hover:text-indigo-600 md:mr-8 text-lg md:text-sm font-bold tracking-wide my-4 md:my-0">
                    Logout
                  </a>
                  <a href="{% url 'savethehawkers:users' user.username %}" style = "color: maroon; font-weight: bolder;" class="transition-all duration-100 ease-in-out pb-1 border-b-2 text-indigo-500 border-transparent hover:border-indigo-300
                  hover:text-indigo-600 md:mr-8 text-lg md:text-sm font-bold tracking-wide my-4 md:my-0">
                    {{user.username}}
                  </a>
                  {% else %}
                  <a href="{% url 'savethehawkers:login' %}" class="transition-all duration-100 ease-in-out pb-1 border-b-2 text-indigo-500 border-transparent hover:border-indigo-300
                  hover:text-indigo-600 md:mr-8 text-lg md:text-sm font-bold tracking-wide my-4 md:my-0">
                    Login/Sign Up
                  </a>
                  <!-- <button class="border border-transparent rounded font-semibold tracking-wide text-lg md:text-sm px-5 py-3 md:py-2
                  focus:outline-none focus:shadow-outline bg-indigo-600 text-gray-100 hover:bg-indigo-800
                  hover:text-gray-200 transition-all duration-300 ease-in-out my-4 md:my-0 w-full md:w-auto">
                    Sign Up
                  </button> -->
                  {% endif %}
                  
                
                </div>
              </div>
            </div>
          </header>
        <!-- <header>
            <h1>Save The Hawkers</h1>
            <nav>
                <ul>
                    <li><a class="active" href="{% url 'savethehawkers:index' %}">Home</a></li>
                    <li><a href="{% url 'savethehawkers:community' %}">Community</a></li>
                    {% if user.is_authenticated %}
                    <li style = "float:right;"><a href = "{% url 'savethehawkers:users' user.username%}"style = "color:black;">Signed in as <strong>{{ user.username }}</strong>.</a></li>
                    <li><a href="{% url 'savethehawkers:logout' %}">Log Out</a></li>
                    <li><a  href="{% url 'savethehawkers:creations' %}">Create Entry</a></li>

                    {% else %}
                    <li style="float:right">Not signed in</li>
                    <li><a  href="{% url 'savethehawkers:login' %}">Log In/Register</a></li>
                    <li><a  href="{% url 'savethehawkers:creations' %}">Create Entry</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header> -->
        {% block body %}
        {% endblock %}
    </body>
</html>

project/templates/project/name.html
{% extends "project/layout.html" %}
{%load static%}
{% block body %}
<div>
    <form action="{% url 'savethehawkers:index' %}" method = "POST">
        {%csrf_token%}

        <label for="postalcode">Postal Code:</label><br>
        <input type="text" id="postalcode" name="postalcode" placeholder="Postal Code"><br>


        <label for="stalltype">Stall Type:</label> <br>
        <select name="stalltype" id="stalltype" >
            <option disabled selected value="None"> Stall Type </option>
            <option value="Chinese">Chinese</option>
            <option value="Malay">Malay</option>
            <option value="Indian">Indian</option>
            <option value="Western">Western</option>
            <option value="Dessert">Dessert</option>
            <option value="Drinks">Drinks</option>
            <option value="Snacks">Snacks</option>
            <option value="Vegetarian">Vegetarian</option>
            <option value="Others">Others</option>
        </select><br>

        
        <label for = "search"> Recommendations: </label><br>
        <input id = "search" name = "search" type = "text" placeholder="Search...">
        <dt>{{message}}</dt>
        <input type="submit" value="Submit">
        <br>
    </form>
    <form action="{% url 'savethehawkers:name' %}" method = "POST">
        {%csrf_token%}
        <label for = "name"> Name: </label><br>
        <input id = "name" name = "name" type = "text" placeholder="Search...">
        <dt>{{message2}}</dt>
        <input type="submit" value="Submit">
        <br>
    </form>
</div>

<div class="filter-results" >
    <div class="filter-results-listing">
        {% for stall in stalls %} {% if forloop.counter == 1 %}
        <h3 class="listing-stall"><a href = "{%url 'savethehawkers:info' stall.name%}">{{stall.name}}</a></h3>
        

        <div class="listing-map">
        {%block stalls.image%}{%if stall.image%}
        <td><img src = "{{stall.image.url}}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%else%}
        <td><img src = "{% static 'project/hawk.png'%}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%endif%}{%endblock%}
        </div>

        <p class="listing-address">
        Address: {{stall.address}}</p>

        <p class="listing-opening-hours">
        
        Opening Hours:{{stall.hour}}</p>

        <p class="listing-recommendation">
       
        Recommendation:{{stall.reco}}</p>
        {%endif%}{%empty%}<dt>No results.</dt>
        {%endfor%}
    </div>
    <div class="filter-results-listing">
        {% for stall in stalls %} {% if forloop.counter == 2 %}
        <h3 class="listing-stall"><a href = "{%url 'savethehawkers:info' stall.name%}">{{stall.name}}</a></h3>
        

        <div class="listing-map">
        {%block stalls.image2%}{%if stall.image%}
        <td><img src = "{{stall.image.url}}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%else%}
        <td><img src = "{% static 'project/hawk.png'%}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%endif%}{%endblock%}
        </div>

        <p class="listing-address">
        Address: {{stall.address}}</p>

        <p class="listing-opening-hours">
        
        Opening Hours:{{stall.hour}}</p>

        <p class="listing-recommendation">
       
        Recommendation:{{stall.reco}}</p>
        {%endif%}{%empty%}<dt>No results.</dt>
        {%endfor%}
    </div>
    <div class="filter-results-listing">
        {% for stall in stalls %} {% if forloop.counter == 3 %}
        <h3 class="listing-stall"><a href = "{%url 'savethehawkers:info' stall.name%}">{{stall.name}}</a></h3>
        

        <div class="listing-map">
        {%block stalls.image3%}{%if stall.image%}
        <td><img src = "{{stall.image.url}}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%else%}
        <td><img src = "{% static 'project/hawk.png'%}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%endif%}{%endblock%}
        </div>

        <p class="listing-address">
        Address: {{stall.address}}</p>

        <p class="listing-opening-hours">
        
        Opening Hours:{{stall.hour}}</p>

        <p class="listing-recommendation">
       
        Recommendation:{{stall.reco}}</p>
        {%endif%}{%empty%}<dt>No results.</dt>
        {%endfor%}
    </div>
    <div class="filter-results-listing">
        {% for stall in stalls %} {% if forloop.counter == 4 %}
        <h3 class="listing-stall"><a href = "{%url 'savethehawkers:info' stall.name%}">{{stall.name}}</a></h3>
        

        <div class="listing-map">
        {%block stalls.image4%}{%if stall.image%}
        <td><img src = "{{stall.image.url}}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%else%}
        <td><img src = "{% static 'project/hawk.png'%}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%endif%}{%endblock%}
        </div>

        <p class="listing-address">
        Address: {{stall.address}}</p>

        <p class="listing-opening-hours">
        
        Opening Hours:{{stall.hour}}</p>

        <p class="listing-recommendation">
       
        Recommendation:{{stall.reco}}</p>
        {%endif%}{%empty%}<dt>No results.</dt>
        {%endfor%}
    </div>
    <div class="filter-results-listing">
        {% for stall in stalls %} {% if forloop.counter == 5 %}
        <h3 class="listing-stall"><a href = "{%url 'savethehawkers:info' stall.name%}">{{stall.name}}</a></h3>
        

        <div class="listing-map">
        {%block stalls.image5%}{%if stall.image%}
        <td><img src = "{{stall.image.url}}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%else%}
        <td><img src = "{% static 'project/hawk.png'%}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%endif%}{%endblock%}
        </div>

        <p class="listing-address">
        Address: {{stall.address}}</p>

        <p class="listing-opening-hours">
        
        Opening Hours:{{stall.hour}}</p>

        <p class="listing-recommendation">
       
        Recommendation:{{stall.reco}}</p>
        {%endif%}{%empty%}<dt>No results.</dt>
        {%endfor%}
    </div>
    <div class="filter-results-listing">
        {% for stall in stalls %} {% if forloop.counter == 6 %}
        <h3 class="listing-stall"><a href = "{%url 'savethehawkers:info' stall.name%}">{{stall.name}}</a></h3>
        

        <div class="listing-map">
        {%block stalls.image6%}{%if stall.image%}
        <td><img src = "{{stall.image.url}}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%else%}
        <td><img src = "{% static 'project/hawk.png'%}" style="position: relative; height: 100%; width: 100%;"  width="240" height="180" style="border:0;" allowfullscreen="" loading="lazy" id = "map"></td>
        {%endif%}{%endblock%}
        </div>

        <p class="listing-address">
        Address: {{stall.address}}</p>

        <p class="listing-opening-hours">
        
        Opening Hours:{{stall.hour}}</p>

        <p class="listing-recommendation">
       
        Recommendation:{{stall.reco}}</p>
        {%endif%}{%empty%}<dt>No results.</dt>
        {%endfor%}
    </div>
    
{% endblock %}